<?php 

  global $layout_callbacks;

  $layout_callbacks = array(
    "section_title" => array("meteor_section_title", 12),
    "meteor_slider" => array("meteor_slider", 6),
    "meteor_slider_fullwidth" => array("meteor_slider", 12),
    "meteor_vslider" => array("meteor_slider", 6),
    "meteor_vslider_fullwidth" => array("meteor_slider", 12),
    "revslider" => array("meteor_slider_bundle", 3),
    "revslider_fullwidth" => array("meteor_slider_bundle", 12),
    "layerslider" => array("meteor_slider_bundle", 3),
    "layerslider_fullwidth" => array("meteor_slider_bundle", 12),
    "cuteslider" => array("meteor_slider_bundle", 3),
    "cuteslider_fullwidth" => array("meteor_slider_bundle", 12),
    "content" => array("meteor_content", 3),
    "content_fullwidth" => array("meteor_content", 12),
    "sidebar" => array("meteor_sidebar", 3),
    "post_content" => array("meteor_single_post", 3),
    "page_content" => array("meteor_single_post", 3),
    "blog_posts" => array("meteor_blog_posts", 3),
    "blog_portfolio_posts" => array("meteor_blog_posts", 3),
    "query_posts" => array("meteor_blog_posts", 3),
    "meteor_posts" => array("meteor_posts", 3),
    "meteor_portfolio_posts" => array("meteor_posts", 3),
    "meteor_gallery" => array("meteor_gallery_shortcode", 3),
    "meteor_posts_scroller" => array("meteor_posts_scroller", 3),
    "meteor_portfolio_posts_scroller" => array("meteor_posts_scroller", 3),
    "meteor_aside_posts" => array("meteor_aside_posts", 6),
    "meteor_aside_portfolio_posts" => array("meteor_aside_posts", 6),
    "vector_icon_posts" => array("meteor_vector_icon_posts", 3),
    "image_icon_posts" => array("meteor_image_icon_posts", 3),
    "quote" => array("meteor_quote", 6),
    "shortcode" => array("meteor_content", 3),
    "pagination" => array("meteor_pagination", 6),
    "meteor_cta" => array("meteor_cta", 3),
    "meteor_cta_fullwidth" => array("meteor_cta", 12),
    "logo_display" => array("meteor_logo_display", 3),
    "logo_scroller" => array("meteor_logo_scroller", 12),
    "google_map" => array("meteor_google_map", 3),
    "google_map_fullwidth" => array("meteor_google_map", 12),
    "pricing_boxes" => array("meteor_pricing", 3),
    "php_code" => array("php_code_component", 3),
    "php_code_no_output" => array("php_code_component", 12),
    "layout_in_layout" => array("layout_in_layout_component", 3),
    "layout_in_layout_fullwidth" => array("layout_in_layout_component", 12)
  );

?>